/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.digimonproyect.view;

import com.mycompany.digimonproyect.model.digimon.Digimon;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author jsbje
 */
public class InformationDigimonDialog extends javax.swing.JDialog {

    /**
     * Creates new form InformationDigimonDialog
     */
    public InformationDigimonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public InformationDigimonDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        digimonPanel = new javax.swing.JPanel();
        digimonLabel = new javax.swing.JLabel();
        xAntiBodyLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        attributesLabel = new javax.swing.JLabel();
        attributesScrollPane = new javax.swing.JScrollPane();
        attributesList = new javax.swing.JList<>();
        skillLabel = new javax.swing.JLabel();
        skillScrollPane = new javax.swing.JScrollPane();
        skillList = new javax.swing.JList<>();
        fieldLabel = new javax.swing.JLabel();
        fieldScrollPane = new javax.swing.JScrollPane();
        fieldsList = new javax.swing.JList<>();
        cancelButton = new javax.swing.JButton();
        evolutionButton = new javax.swing.JButton();
        levelsLabel = new javax.swing.JLabel();
        levelsScrollPane = new javax.swing.JScrollPane();
        levelsList = new javax.swing.JList<>();
        typeLabel = new javax.swing.JLabel();
        typeScrollPane = new javax.swing.JScrollPane();
        TypesList = new javax.swing.JList<>();
        createLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        digimonPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout digimonPanelLayout = new javax.swing.GroupLayout(digimonPanel);
        digimonPanel.setLayout(digimonPanelLayout);
        digimonPanelLayout.setHorizontalGroup(
            digimonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        digimonPanelLayout.setVerticalGroup(
            digimonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        digimonLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        digimonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digimonLabel.setText("");

        xAntiBodyLabel.setText("");

        descriptionLabel.setText("Description: ");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(255, 255, 255));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setBorder(null);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        attributesLabel.setText("Attributes:");

        attributesList.setBorder(null);
        attributesScrollPane.setViewportView(attributesList);

        skillLabel.setText("Skills: ");

        skillScrollPane.setViewportView(skillList);

        fieldLabel.setText("Fields: ");

        fieldsList.setBorder(null);
        fieldScrollPane.setViewportView(fieldsList);

        cancelButton.setText("Cancel");

        evolutionButton.setText("Show evolution chain...");

        levelsLabel.setText("Levels: ");

        levelsList.setBorder(null);
        levelsScrollPane.setViewportView(levelsList);

        typeLabel.setText("Types: ");

        TypesList.setBorder(null);
        typeScrollPane.setViewportView(TypesList);

        createLabel.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(digimonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(descriptionLabel)
                                    .addGap(4, 4, 4)))
                            .addComponent(levelsLabel)
                            .addComponent(attributesLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(levelsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attributesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(skillLabel)
                                    .addComponent(fieldLabel)
                                    .addComponent(typeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(skillScrollPane)
                                    .addComponent(fieldScrollPane)
                                    .addComponent(typeScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(digimonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 75, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(xAntiBodyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(evolutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(digimonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digimonLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descriptionLabel)
                            .addComponent(descriptionScrollPane)
                            .addComponent(skillLabel)
                            .addComponent(skillScrollPane))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(fieldLabel)
                            .addComponent(attributesLabel)
                            .addComponent(attributesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(levelsScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(typeScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(levelsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xAntiBodyLabel)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(evolutionButton)
                            .addComponent(cancelButton))
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setImageLogoPanel(Image image, JPanel panel) {
        panel.removeAll();
        JPanel panelConImagen = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (image != null) {

                    g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        panelConImagen.setPreferredSize(panel.getSize());
        panelConImagen.setLayout(new BorderLayout());

        panel.setLayout(new BorderLayout());
        panel.add(panelConImagen, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
    public void createPanel(JPanel panel, String route) throws MalformedURLException, IOException {
        Image image = getImage(route);
        setImageLogoPanel(image, panel);
    }
    public Image getImage(String route) throws IOException {
        Image image = null;
        if (route.contains("https://")) {
            URL url = new URL(route);
            image = ImageIO.read(url);
        } else {
            image = new ImageIcon(route).getImage();
        }
        return image;
    }
    
    public JPanel getDigimonPanel (){
        return this.digimonPanel;
    }
    public void setDescriptioAreaText(String value){
        this.descriptionTextArea.setText(value);
    }
    public void setDigimonLabel(String value){
        this.digimonLabel.setText(value);
    }
    public void setXAntiBodyLabel(String  value){
        this.xAntiBodyLabel.setText(value);
    }

    public void setJListModel(DefaultListModel<String> model, Digimon digimon, JList list, JScrollPane pane) {
        if (list == null) {
            list = new JList<String>(model);
            pane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            pane = new JScrollPane(list);
        } else {
            list.setModel(model);
        }
    }
    
    public void setCancelButtonListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    public void setShowEvolutionsButtoonListener(ActionListener al){
        this.evolutionButton.addActionListener(al);
    }

    public JList<String> getAttributesList() {
        return attributesList;
    }
    public JList<String> getFieldsList() {
        return fieldsList;
    }
    public JList<String> getSkillList() {
        return skillList;
    }
    public JList<String> getTypesList() {
        return TypesList;
    }
    public JList<String> getLevelsList() {
        return levelsList;
    }
    public JScrollPane getAttributesScrollPane() {
        return attributesScrollPane;
    }
    public JScrollPane getDescriptionScrollPane() {
        return descriptionScrollPane;
    }
    public JScrollPane getFieldScrollPane() {
        return fieldScrollPane;
    }
    public JScrollPane getLevelsScrollPane() {
        return levelsScrollPane;
    }
    public JScrollPane getTypeScrollPane() {
        return typeScrollPane;
        }
    public JScrollPane getSkillScrollPane() {
        return skillScrollPane;
    }
    public JTextArea getDescriptionTextArea() {
        return descriptionTextArea;
    }

    public void setCreateLabel(String value) {
        this.createLabel.setText(value);
    }
    

    public void configurateTextArea(JScrollPane pane, JTextArea textArea){
        pane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> TypesList;
    private javax.swing.JLabel attributesLabel;
    private javax.swing.JList<String> attributesList;
    private javax.swing.JScrollPane attributesScrollPane;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel digimonLabel;
    private javax.swing.JPanel digimonPanel;
    private javax.swing.JButton evolutionButton;
    private javax.swing.JLabel fieldLabel;
    private javax.swing.JScrollPane fieldScrollPane;
    private javax.swing.JList<String> fieldsList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JList<String> levelsList;
    private javax.swing.JScrollPane levelsScrollPane;
    private javax.swing.JLabel skillLabel;
    private javax.swing.JList<String> skillList;
    private javax.swing.JScrollPane skillScrollPane;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JScrollPane typeScrollPane;
    private javax.swing.JLabel xAntiBodyLabel;
    // End of variables declaration//GEN-END:variables
}
