/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.digimonproyect.view;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu09@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        sessionMenuItem = new javax.swing.JMenuItem();
        digimonMenuItem = new javax.swing.JMenuItem();
        personalListMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        optionsMenu.setText("Options");

        sessionMenuItem.setText("Session..");
        optionsMenu.add(sessionMenuItem);

        digimonMenuItem.setText("DigimonAPI..");
        optionsMenu.add(digimonMenuItem);

        personalListMenuItem.setText("Personal list..");
        optionsMenu.add(personalListMenuItem);

        quitMenuItem.setText("Quit");
        optionsMenu.add(quitMenuItem);

        mainMenuBar.add(optionsMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addQuitMenuItemActionListener(ActionListener al){
        this.quitMenuItem.addActionListener(al);
    }
    public void addPersonalListMenuItemActionListener(ActionListener al){
        this.personalListMenuItem.addActionListener(al);
    }
    public void addDigimonMenuItemActionListener(ActionListener al){
        this.digimonMenuItem.addActionListener(al);
    }
    public void addSessionMenuItemActionListener(ActionListener al){
        this.sessionMenuItem.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem digimonMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem personalListMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem sessionMenuItem;
    // End of variables declaration//GEN-END:variables
}
