/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.digimonproyect.view;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author dam2_alu09@inf.ald
 */
public class PersonalListJDialog extends javax.swing.JDialog {

    /**
     * Creates new form PersonalListJDialog
     */
    public PersonalListJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addTableRenderer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digimonScrollPane = new javax.swing.JScrollPane();
        digimonTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        cloneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        digimonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Icon", "Nickname", "Name", "XAntibody"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        digimonTable.setRowHeight(80);
        digimonTable.getTableHeader().setReorderingAllowed(false);
        digimonScrollPane.setViewportView(digimonTable);

        titleLabel.setText("Personal List");

        modifyButton.setText("Modify...");

        showButton.setText("Show Info..");

        deleteButton.setText("Delete");

        createButton.setText("Create");

        cloneButton.setText("Clone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cloneButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showButton))
                            .addComponent(digimonScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digimonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyButton)
                    .addComponent(deleteButton)
                    .addComponent(showButton)
                    .addComponent(createButton)
                    .addComponent(cloneButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDeleteButtonActionListener(ActionListener al){
        this.deleteButton.addActionListener(al);
    }
    public void setModifyButtonActionListener(ActionListener al){
        this.modifyButton.addActionListener(al);
    }
    public void setShowButtonActionListener(ActionListener al){
        this.showButton.addActionListener(al);
    }
    public void setCreateButtonActionListener(ActionListener al){
        this.createButton.addActionListener(al);
    }
    public void setCloneButtonActionListener(ActionListener al){
        this.cloneButton.addActionListener(al);
    }
    public void setTitleLabel(String s){
        this.titleLabel.setText(s);
    }
    public int getSelectionColumn(){
        return this.digimonTable.getSelectedColumn();
    }
    public int getSelectionRow(){
        return this.digimonTable.getSelectedRow();
    }

    public void addRowTable(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.digimonTable.getModel();
        model.addRow(row);
    }

    private void addTableRenderer() {
        digimonTable.getColumnModel().getColumn(0).setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel();
                label.setHorizontalAlignment(JLabel.CENTER);

                if (value instanceof ImageIcon) {
                    label.setIcon((ImageIcon) value);
                    label.setText("");
                } else {
                    label.setIcon(null);
                    label.setText(value != null ? value.toString() : "");
                }

                label.setOpaque(true);
                label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                label.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());

                return label;
            }
        });
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        digimonTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        digimonTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
    }
    public void clearTable() {
        DefaultTableModel model=(DefaultTableModel) this.digimonTable.getModel();
        model.setRowCount(0);
        digimonTable.clearSelection();
        digimonTable.revalidate();
        digimonTable.repaint();
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cloneButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane digimonScrollPane;
    private javax.swing.JTable digimonTable;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
